a

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -45,102 +45,102 @@ jobs:
           aws-region: ${{ env.aws_region }}
           role-session-name: github-actions
 
-      - name: Terraform Apply ECR
-        run: |
-          terraform init -upgrade
-          terraform apply -auto-approve -target=module.ecr
+      # - name: Terraform Apply ECR
+      #   run: |
+      #     terraform init -upgrade
+      #     terraform apply -auto-approve -target=module.ecr
 
-      - name: Login to ECR
-        run: |
-          aws ecr get-login-password --region ${{ env.aws_region }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com
+      # - name: Login to ECR
+      #   run: |
+      #     aws ecr get-login-password --region ${{ env.aws_region }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com
 
-      - name: Build Docker Image
-        run: |
-          docker build -t ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ env.repo_name }}:${{ env.image_tag }} ./python-docker
+      # - name: Build Docker Image
+      #   run: |
+      #     docker build -t ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ env.repo_name }}:${{ env.image_tag }} ./python-docker
 
-      - name: Push Docker Image to ECR
-        run: |
-          docker push ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ env.repo_name }}:${{ env.image_tag }}
+      # - name: Push Docker Image to ECR
+      #   run: |
+      #     docker push ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ env.repo_name }}:${{ env.image_tag }}
 
-      - name: Terraform Apply Infrastructure
-        run: |
-          terraform apply -auto-approve
+      # - name: Terraform Apply Infrastructure
+      #   run: |
+      #     terraform apply -auto-approve
 
-      - name: Update kubeconfig
-        run: |
-          aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}
+      # - name: Update kubeconfig
+      #   run: |
+      #     aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }} > /dev/null 
 
-      - name: Patch aws-auth ConfigMap
-        run: |
-          cat <<EOF | kubectl apply -f -
-          apiVersion: v1
-          kind: ConfigMap
-          metadata:
-            name: aws-auth
-            namespace: kube-system
-          data:
-            mapUsers: |
-              - userarn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:user/${{secrets.AWS_USER}}
-                username: ${{secrets.AWS_USER}}
-                groups:
-                  - system:masters
-          EOF
+      # - name: Patch aws-auth ConfigMap
+      #   run: |
+      #     cat <<EOF | kubectl apply -f -
+      #     apiVersion: v1
+      #     kind: ConfigMap
+      #     metadata:
+      #       name: aws-auth
+      #       namespace: kube-system
+      #     data:
+      #       mapUsers: |
+      #         - userarn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:user/${{secrets.AWS_USER}}
+      #           username: ${{secrets.AWS_USER}}
+      #           groups:
+      #             - system:masters
+      #     EOF
 
-      - name: Helm Install ArgoCD
-        run: |
-          aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}
-          helm repo add argo https://argoproj.github.io/argo-helm
-          helm repo update
-          helm upgrade --install argocd argo/argo-cd \
-            --namespace argocd \
-            --create-namespace \
-            --set server.service.type=LoadBalancer \
-            --set server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="classic"
+      # - name: Helm Install ArgoCD
+      #   run: |
+      #     aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}
+      #     helm repo add argo https://argoproj.github.io/argo-helm
+      #     helm repo update
+      #     helm upgrade --install argocd argo/argo-cd \
+      #       --namespace argocd \
+      #       --create-namespace \
+      #       --set server.service.type=LoadBalancer \
+      #       --set server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="classic"
 
-      - name: Get VPC ID by Name
-        run: |
-          export VPC_ID=$(aws ec2 describe-vpcs \
-            --filters "Name=tag:Name,Values=${{ env.vpc_name }}" \
-            --query "Vpcs[0].VpcId" \
-            --output text)
-          echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV
+      # - name: Get VPC ID by Name
+      #   run: |
+      #     export VPC_ID=$(aws ec2 describe-vpcs \
+      #       --filters "Name=tag:Name,Values=${{ env.vpc_name }}" \
+      #       --query "Vpcs[0].VpcId" \
+      #       --output text)
+      #     echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV
 
-      - name: Install ALB Controller via Helm
-        run: |
-          helm repo add eks https://aws.github.io/eks-charts
-          helm repo update
-          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
-            --namespace kube-system \
-            --create-namespace \
-            --set clusterName=${{ env.cluster_name }} \
-            --set region=${{ env.aws_region }} \
-            --set vpcId=${{ env.VPC_ID }} \
-            --set serviceAccount.create=true \
-            --set serviceAccount.name=aws-load-balancer-controller \
-            --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/eks-lb-controller-role" \
-            --set cleanupOnDelete=true
-          kubectl -n kube-system rollout status deployment/aws-load-balancer-controller --timeout=2m
+      # - name: Install ALB Controller via Helm
+      #   run: |
+      #     helm repo add eks https://aws.github.io/eks-charts
+      #     helm repo update
+      #     helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
+      #       --namespace kube-system \
+      #       --create-namespace \
+      #       --set clusterName=${{ env.cluster_name }} \
+      #       --set region=${{ env.aws_region }} \
+      #       --set vpcId=${{ env.VPC_ID }} \
+      #       --set serviceAccount.create=true \
+      #       --set serviceAccount.name=aws-load-balancer-controller \
+      #       --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/eks-lb-controller-role" \
+      #       --set cleanupOnDelete=true
+      #     kubectl -n kube-system rollout status deployment/aws-load-balancer-controller --timeout=2m
 
 
-      - name: Install ExternalDNS via Helm
-        continue-on-error: true
-        run: |
-          helm repo add external-dns https://kubernetes-sigs.github.io/external-dns/
-          helm repo update
-          helm upgrade --install external-dns external-dns/external-dns \
-            --namespace kube-system \
-            --create-namespace \
-            --set provider=aws \
-            --set region=${{ env.aws_region }} \
-            --set domainFilters[0]=saharbittman.com \
-            --set policy=sync \
-            --set sources[0]=ingress \
-            --set sources[1]=service \
-            --set serviceAccount.create=true \
-            --set serviceAccount.name=external-dns \
-            --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/eks-external-dns-role" \
-            --set txtOwnerId=${{ env.cluster_name }} \
-            --set cleanupOnDelete=true
+      # - name: Install ExternalDNS via Helm
+      #   continue-on-error: true
+      #   run: |
+      #     helm repo add external-dns https://kubernetes-sigs.github.io/external-dns/
+      #     helm repo update
+      #     helm upgrade --install external-dns external-dns/external-dns \
+      #       --namespace kube-system \
+      #       --create-namespace \
+      #       --set provider=aws \
+      #       --set region=${{ env.aws_region }} \
+      #       --set domainFilters[0]=saharbittman.com \
+      #       --set policy=sync \
+      #       --set sources[0]=ingress \
+      #       --set sources[1]=service \
+      #       --set serviceAccount.create=true \
+      #       --set serviceAccount.name=external-dns \
+      #       --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/eks-external-dns-role" \
+      #       --set txtOwnerId=${{ env.cluster_name }} \
+      #       --set cleanupOnDelete=true
       
       - name: Download and Install ArgoCD CLI
         run: |
@@ -150,6 +150,7 @@ jobs:
           argocd version --client
 
       - name: Login to ArgoCD and create/update app
+        continue-on-error: true
         run: |
           aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}
           ARGOCD_ADMIN_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode)
@@ -184,16 +185,18 @@ jobs:
   #       with:
   #         terraform_version: ${{ env.terraform_version }}
 
-  #     - name: Configure AWS credentials via OIDC
-  #       uses: aws-actions/configure-aws-credentials@v3
-  #       with:
-  #         role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-  #         aws-region: ${{ env.aws_region }}
-  #         role-session-name: github-actions
+      # - name: Configure AWS credentials via OIDC
+      #   uses: aws-actions/configure-aws-credentials@v3
+      #   with:
+      #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+      #     aws-region: ${{ env.aws_region }}
+      #     role-session-name: github-actions
 
   #     - name: Destroy EKS
   #       run: |
-  #         aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}
+  #         aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }} > /dev/null
+  #         kubectl patch ingress flask-app-ingress -p '{"metadata":{"finalizers":null}}' --type=merge
+  #         kubectl delete ingress flask-app-ingress || true        
   #         kubectl patch app flask -n argocd -p '{"metadata":{"finalizers":null}}' --type=merge
   #         kubectl delete applications -n argocd flask
   #         helm uninstall argocd -n argocd || true
