a

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -87,16 +87,16 @@ jobs:
                   - system:masters
           EOF
 
-      # - name: Helm Install ArgoCD
-      #   run: |
-      #     aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}
-      #     helm repo add argo https://argoproj.github.io/argo-helm
-      #     helm repo update
-      #     helm upgrade --install argocd argo/argo-cd \
-      #       --namespace argocd \
-      #       --create-namespace \
-      #       --set server.service.type=LoadBalancer \
-      #       --set server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="classic"
+      - name: Helm Install ArgoCD
+        run: |
+          aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}
+          helm repo add argo https://argoproj.github.io/argo-helm
+          helm repo update
+          helm upgrade --install argocd argo/argo-cd \
+            --namespace argocd \
+            --create-namespace \
+            --set server.service.type=LoadBalancer \
+            --set server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="classic"
 
       - name: Get VPC ID by Name
         run: |
@@ -143,7 +143,6 @@ jobs:
             --set txtOwnerId=${{ env.cluster_name }} \
             --set cleanupOnDelete=true
       
-      # הוסף את ה-Step הזה לפני השימוש ב-argocd CLI
       - name: Download and Install ArgoCD CLI
         run: |
           # הורדת הגרסה האחרונה
@@ -175,43 +174,43 @@ jobs:
             --upsert
 
 
-  # destroy_pipeline:
-  #   runs-on: ubuntu-latest
-  #   if: ${{ github.event.inputs.action == 'destroy' || failure() }}
-  #   needs: ci_cd_pipeline
+  destroy_pipeline:
+    runs-on: ubuntu-latest
+    if: ${{ github.event.inputs.action == 'destroy' || failure() }}
+    needs: ci_cd_pipeline
 
-  #   steps:
-  #     - name: Checkout repo
-  #       uses: actions/checkout@v4
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
 
-  #     - name: Setup Terraform
-  #       uses: hashicorp/setup-terraform@v2
-  #       with:
-  #         terraform_version: ${{ env.terraform_version }}
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: ${{ env.terraform_version }}
 
-  #     - name: Configure AWS credentials via OIDC
-  #       uses: aws-actions/configure-aws-credentials@v3
-  #       with:
-  #         role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-  #         aws-region: ${{ env.aws_region }}
-  #         role-session-name: github-actions
+      - name: Configure AWS credentials via OIDC
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+          aws-region: ${{ env.aws_region }}
+          role-session-name: github-actions
 
-  #     - name: Destroy EKS
-  #       run: |
-  #         aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}
-  #         helm uninstall argocd -n argocd || true
-  #         terraform init -upgrade
-  #         terraform destroy -target=module.eks -auto-approve || true
+      - name: Destroy EKS
+        run: |
+          aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}
+          helm uninstall argocd -n argocd || true
+          terraform init -upgrade
+          terraform destroy -target=module.eks -auto-approve || true
 
-  #     - name: Remove Security Groups from VPC
-  #       run: |
-  #         for sg in $(aws ec2 describe-security-groups --region ${{ env.aws_region }} \
-  #           --query 'SecurityGroups[?GroupName!=`default`].GroupId' --output text); do
-  #           echo "Trying to delete SG $sg"
-  #           aws ec2 delete-security-group --region ${{ env.aws_region }} --group-id $sg || echo "Cannot delete $sg, still in use"
-  #         done
+      - name: Remove Security Groups from VPC
+        run: |
+          for sg in $(aws ec2 describe-security-groups --region ${{ env.aws_region }} \
+            --query 'SecurityGroups[?GroupName!=`default`].GroupId' --output text); do
+            echo "Trying to delete SG $sg"
+            aws ec2 delete-security-group --region ${{ env.aws_region }} --group-id $sg || echo "Cannot delete $sg, still in use"
+          done
 
-  #     - name: Terraform Destroy Remaining Resources
-  #       run: |
-  #         terraform init -upgrade
-  #         terraform destroy -auto-approve || true
+      - name: Terraform Destroy Remaining Resources
+        run: |
+          terraform init -upgrade
+          terraform destroy -auto-approve || true
